Prepare for scap deployment
This adds arclamp-grep.py and flamegraph.pl, which were present in
Puppet but missing here.  The flamegraph.pl license is also included,
per that script's license.  I renamed doc → docs so that we can
include flamegraph.pl unmodified (the script header references the
latter directory name).

The change to remove these files from Puppet is I09095f65.

Bug: T200109
Change-Id: I97d946e64536f5fafea67444084c6c59be528889

diff --git a/arclamp-generate-svgs b/arclamp-generate-svgs
--- a/arclamp-generate-svgs
+++ b/arclamp-generate-svgs
@@ -1,4 +1,15 @@
 #!/bin/bash
+
+# Prefer flamegraph.pl in current directory.  If not found, look in PATH.
+flamegraph=`dirname $0`/flamegraph.pl
+if [ ! -x "$flamegraph" ]; then
+    flamegraph=`which flamegraph.pl`
+    if [ ! -x "$flamegraph" ]; then
+        echo "$0: cannot execute flamegraph.pl" >&2
+        exit 1
+    fi
+fi
+
 set -e
 set +C  # OK to clobber out-of-date SVGs
 shopt -s globstar nullglob
@@ -19,11 +30,11 @@ for log in /srv/arclamp/**/*.log; do
     mkdir -m0755 -p "$(dirname $svg)"
     [ ! -f "$svg" -o "$svg" -ot "$log" ] && {
         echo "Generating ${svg}..."
-        nice /usr/local/bin/flamegraph.pl --minwidth=1 --title="$title" "$log" | gzip -9 > "$svg"
+        nice $flamegraph --minwidth=1 --title="$title" "$log" | gzip -9 > "$svg"
     }
     [ ! -f "$rsvg" -o "$rsvg" -ot "$log" ] && {
         echo "Generating ${rsvg}..."
-        nice /usr/local/bin/flamegraph.pl --minwidth=1 --reverse --colors=blue --title="$title - reversed" "$log" | gzip -9 > "$rsvg"
+        nice $flamegraph --minwidth=1 --reverse --colors=blue --title="$title - reversed" "$log" | gzip -9 > "$rsvg"
     }
 done
 
